packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  dev:
    '@antfu/eslint-config': ^2.18.1
    '@types/node': ^20.12.12
    bumpp: ^9.4.1
    eslint: ^9.3.0
    esno: ^4.7.0
    lint-staged: ^15.2.2
    simple-git-hooks: ^2.11.1
    typescript: ^5.4.5
    unbuild: ^3.5.0
    vite: ^5.2.11
    vitest: ^3.1.3
    vite-tsconfig-paths: 6.0.0-beta.3

  docs:
    typedoc-vitepress-theme: ^1.1.2
    vitepress: ^1.6.3
    typedoc-plugin-markdown: ^4.6.3
    typedoc: ^0.28.4

  test:
    happy-dom: ^17.4.7

  build:
    query-string: ^9.1.2
    decimal.js: ^10.5.0
